# Generated by Django 4.0.1 on 2022-01-25 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_address', models.CharField(max_length=255)),
                ('employee_phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('employee_role', models.CharField(choices=[('A', 'Admin'), ('R', 'Receptionist')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_qunatity', models.IntegerField()),
                ('product_expiry', models.DateField()),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transction',
            fields=[
                ('transction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_sum', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
