# Generated by Django 4.0.1 on 2022-01-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_employee_employee_id_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
    ]
